import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ['latin'], weight: ["300", "400", "500", "600", "700", "800"]})

export const metadata = {
  title: "We frame Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
